set nocompatible
syntax on
let $VIMHOME = $HOME."/.vim"
filetype on


set cursorline
set showmode
set history=1000
set undolevels=100
set ruler

"Search and replace
set incsearch

"Spaces and tabs
set shiftwidth=4
set softtabstop=4
set tabstop=8
set shiftround
set expandtab

set autoindent
set copyindent

"Tabs
map <silent><C-m> :tabnext<CR>
map <silent><C-n> :tabprevious<CR>
map <silent><C-t> :tabnew<CR>

""Colors
map <silent><F9> :set background=dark<CR>

""Number
set number
map <silent><F2> :set invnumber<CR>

""Paste options

map <silent><F5> :set paste<CR>
map <silent><F6> :set nopaste<CR>


"Saving
map <silent><F10> :wq!<CR>
imap qq <Esc>:q!<CR>
imap ww <Esc>:wq<CR>

"Directory
map <silent><F4> :op .<CR>
"set wildignore+=.git/*,.svn/*,.hg/*,_darcs/*,build/*,dist/*,*.o,*.so,*.polorScheme * highlight BadWhitespace ctermbg=red guibg=red 
" highlight wrong spaces and tabs
autocmd ColorScheme * highlight BadWhitespace ctermbg=red guibg=red
colorscheme default " hack to force the highlight group to be created
match BadWhitespace /^\t\+/
match BadWhitespace /^\s\+/
match BadWhitespace /\t\+$/
match BadWhitespace /\s\+$/
filetype plugin on

" F3 = OmniComplete
imap <f3> <c-x><c-o>

"NERDTree
map <silent><C-r> :NERDTreeToggle <CR>


" Configuración del autocompletado inteligente (el de Python necesita un Vim
" compilado contra las librerías de Python para funcionar)
autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS


"Ctags Configuration

let Tlist_Ctags_Cmd = "/usr/bin/ctags"
let Tlist_WinWidth = 50
map <F7> :TlistToggle<cr>
