alias s='sudo'

alias ll='ls -la'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias sup='svn up'
alias sadd='svn add'
alias sci='svn ci'
alias sstatus='svn status'

alias change_dns="s sed -i s/'^nameserver .*'/'nameserver 8.8.8.8'/g /etc/resolv.conf"

alias top10="ps -eo pcpu,pid,user,args | sort -k 1 -r | head -10"
 
#Work
alias vpnk="s vpnc-disconnect"
alias vpnc="s vpnc-connect"

alias dpkg-search= "dpkg -l | grep "


#Asterisk
alias ast_restart= "/etc/init.d/asterisk start"
alias ast_channels= "asterisk -rnx \"core show channels\""
alias ast_pri= "asterisk -rnx \"pri show spams\""
